// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/yap"

const _ = true

type foo struct {
	yap.App
}
//line staticfile/foo_yap.gox:1
func (this *foo) MainEntry() {
//line staticfile/foo_yap.gox:1:1
	this.Static__0("/pub", this.FS("public"))
//line staticfile/foo_yap.gox:2:1
	this.Static__0("/")
//line staticfile/foo_yap.gox:4:1
	this.Run(":8080")
}
func main() {
//line staticfile/foo_yap.gox:4:1
	yap.Gopt_App_Main(new(foo))
}
