// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/yap"

const _ = true

type hello struct {
	yap.App
}
//line hello/hello_yap.gox:1
func (this *hello) MainEntry() {
//line hello/hello_yap.gox:1:1
	this.Static__0("/foo", this.FS("public"))
//line hello/hello_yap.gox:2:1
	this.Static__0("/")
//line hello/hello_yap.gox:4:1
	this.Get("/p/:id", func(ctx *yap.Context) {
//line hello/hello_yap.gox:5:1
		ctx.Json__1(map[string]string{"id": ctx.Param("id"), "title": "hello", "author": "tsingbx"})
	})
//line hello/hello_yap.gox:16:1
	this.Run(":8000")
}
func main() {
//line hello/hello_yap.gox:16:1
	yap.Gopt_App_Main(new(hello))
}
