// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/yap/test"
	"github.com/goplus/yap/ytest"
	"strconv"
	"testing"
)

type case_example struct {
	ytest.Case
}
//line yaptest/example_ytest.gox:1
func (this *case_example) Main() {
//line yaptest/example_ytest.gox:1:1
	this.Host("https://example.com", "http://localhost:8888")
//line yaptest/example_ytest.gox:2:1
	this.Host("https://hello.com", "http://localhost:8000")
//line yaptest/example_ytest.gox:5:1
	this.Run("urlWithVar", func() {
//line yaptest/example_ytest.gox:6:1
		id := "123"
//line yaptest/example_ytest.gox:7:1
		this.Get("https://example.com/p/" + id)
//line yaptest/example_ytest.gox:8:1
		this.RetWith(200)
//line yaptest/example_ytest.gox:9:1
		fmt.Println("code:", this.Resp().Code())
//line yaptest/example_ytest.gox:10:1
		fmt.Println("body:", this.Resp().Body())
	})
//line yaptest/example_ytest.gox:13:1
	this.Run("matchWithVar", func() {
//line yaptest/example_ytest.gox:14:1
		code := test.Gopx_Var_Cast__0[int]()
//line yaptest/example_ytest.gox:15:1
		id := 124
//line yaptest/example_ytest.gox:16:1
		this.Get("https://example.com/p/" + strconv.Itoa(id))
//line yaptest/example_ytest.gox:17:1
		this.RetWith(code)
//line yaptest/example_ytest.gox:18:1
		fmt.Println("code:", code)
//line yaptest/example_ytest.gox:19:1
		test.Gopt_Case_MatchAny(this, code, 200)
//line yaptest/example_ytest.gox:20:1
		test.Gopt_Case_MatchTBase(this, id, 124)
	})
//line yaptest/example_ytest.gox:38:1
	this.Run("matchJsonObject", func() {
//line yaptest/example_ytest.gox:39:1
		title := test.Gopx_Var_Cast__0[string]()
//line yaptest/example_ytest.gox:40:1
		author := test.Gopx_Var_Cast__0[string]()
//line yaptest/example_ytest.gox:41:1
		id := "123"
//line yaptest/example_ytest.gox:42:1
		this.Get("https://hello.com/p/" + id)
//line yaptest/example_ytest.gox:43:1
		this.RetWith(200)
//line yaptest/example_ytest.gox:44:1
		this.Json(map[string]string{"title": "hello", "author": "tsingbx"})
//line yaptest/example_ytest.gox:48:1
		fmt.Println("title:", title)
//line yaptest/example_ytest.gox:49:1
		fmt.Println("author:", author)
	})
}
func Test_example(t *testing.T) {
	ytest.Gopt_Case_TestMain(new(case_example), t)
}
