// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/yap"

const _ = true

type blog struct {
	yap.App
}
//line blog/blog_yap.gox:1
func (this *blog) MainEntry() {
//line blog/blog_yap.gox:1:1
	this.Get("/p/:id", func(ctx *yap.Context) {
//line blog/blog_yap.gox:2:1
		ctx.Yap__1("article/article", map[string]string{"id": ctx.Param("id")})
	})
//line blog/blog_yap.gox:7:1
	this.Get("/index/:n", func(ctx *yap.Context) {
//line blog/blog_yap.gox:8:1
		ctx.Yap__1("index", map[string]string{"name": ctx.Param("n")})
	})
//line blog/blog_yap.gox:13:1
	this.Run(":8888")
}
func main() {
//line blog/blog_yap.gox:13:1
	yap.Gopt_App_Main(new(blog))
}
