// Code generated by gop (Go+); DO NOT EDIT.

package main

import "fmt"

const _ = true

type Rect struct {
	Width  int
	Height int
}
//line rect/Rect.gox:5:1
func (this *Rect) Area() int {
//line rect/Rect.gox:6:1
	return this.Width * this.Height
}
//line rect/hello.gop:1
func main() {
//line rect/hello.gop:1:1
	rect := &Rect{10, 20}
//line rect/hello.gop:2:1
	fmt.Println(rect.Area())
}
